import './styles/global.css'

import AuthContext from "./components/AuthContext"
import Layout from "./components/layout"
import getBrandsData from "./lib/getBrandsData"
import getCategoryData from "./lib/getCategoryData"
import getSessionData from "./lib/getSessionData"
import { headers } from 'next/headers';
import { getServerSession } from 'next-auth'
import { authOptions } from '../../pages/api/auth/[...nextauth]'
import { getSession, useSession } from 'next-auth/react'
import { log } from 'console'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export const dynamic = 'force-static'


const languages = ['ae-en', 'ae-ar', 'sa-en', 'sa-ar']

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export default async function RootLayout({ children, params: { lang } }) {
  // if(lang===""){
  //   lang = "ae-en"
  // }
  const pageData = getCategoryData(lang)
  const data = await pageData

  const brandsData = getBrandsData()
  const brands_data = await brandsData

  const session = await getSessionData(headers().get('cookie') ?? '')
  // const session = await getServerSession(authOptions)

  var isArabic = false

  function dirGenerate(lang) {    
    if (lang === 'ae-ar' || lang === 'sa-ar') {
      isArabic = true
      return 'rtl'
    }
    return 'ltl'
  }

  // console.log(session);


  return (
    <html lang="en" dir={dirGenerate(lang)}>
      <body>
        <AuthContext>
          <Layout data={data} brands_data={brands_data} sessionServ={session} isArabic={isArabic} lang={lang}>
            {children}
          </Layout>
        </AuthContext>
      </body>
    </html >
  )
}
